install.packages("remotes")
remotes::install_github("jjesusfilho/tjsp")
install.packages("tidyverse")
remotes::install_github("jjesusfilho/stf")
remotes::install_github("jjesusfilho/stj")
install.packages(c("writexl", "readxl"))
